name: CI/CD Demo Pipeline
on: [push]
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build step (simulated)
        run: echo "Building project..."
      - name: Test step using pytest
        run: |
          python -m pip install pytest
          pytest
      - name: Deploy step (simulated)
        run: echo "Deploying project (demo)..."
